package com.kandouwo.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.kandouwo.model.dao.SplashImage;

import com.kandouwo.model.dao.SplashImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig splashImageDaoConfig;

    private final SplashImageDao splashImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        splashImageDaoConfig = daoConfigMap.get(SplashImageDao.class).clone();
        splashImageDaoConfig.initIdentityScope(type);

        splashImageDao = new SplashImageDao(splashImageDaoConfig, this);

        registerDao(SplashImage.class, splashImageDao);
    }
    
    public void clear() {
        splashImageDaoConfig.getIdentityScope().clear();
    }

    public SplashImageDao getSplashImageDao() {
        return splashImageDao;
    }

}
