package com.kandouwo.model.dao;

import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table splash_image.
 */
public class SplashImage {

    private Long id;
    private Integer version;
    private Long startTime;
    private Long endTime;
    private String imageUrl;
    private String title;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SplashImage() {
    }

    public SplashImage(Long id) {
        this.id = id;
    }

    public SplashImage(Long id, Integer version, Long startTime, Long endTime, String imageUrl, String title) {
        this.id = id;
        this.version = version;
        this.startTime = startTime;
        this.endTime = endTime;
        this.imageUrl = imageUrl;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
